### ISSUE TITLE
Rotation fails with timeout

### ISSUE THREAD

**Issue by bodomic** [mkouhei/backup2swift#29]
Subj while the main functionality works perfectly.

`Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/backup2swift/backup.py", line 77, in backup
    self.backup_file(target_path)
  File "/usr/local/lib/python2.7/dist-packages/backup2swift/backup.py", line 107, in backup_file
    self.rotate(filename, object_name, objects_list)
  File "/usr/local/lib/python2.7/dist-packages/backup2swift/backup.py", line 129, in rotate
    new_object_name)
  File "/usr/local/lib/python2.7/dist-packages/swiftsc/client.py", line 465, in copy
    timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 120, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='storage.files.mo01.cloud.servers.com', port=8080): Read timed out. (read timeout=5.0)
`

File is copied, then operation fails:
`latest-aa                 2016-04-23T08:00:50.134240 b3755c47180bdb629afb59622701142b application/x-bzip2      1073741824
latest-aa_20160424-103151 2016-04-24T07:31:51.132160 b3755c47180bdb629afb59622701142b application/x-bzip2      1073741824
latest-aa_20160424-195043 2016-04-24T16:50:43.877850 b3755c47180bdb629afb59622701142b application/x-bzip2      1073741824
`

Version is v0.9.4.
Please advise.

**Comment by bodomic** [comment]
Sorry, I need a 'timeout' option in config obviously :)
