### ISSUE TITLE
Error : Invalid URL 'None/PCA': No schema supplied.

### ISSUE THREAD

**Issue by fredo-m** [mkouhei/backup2swift#33]
Hi,

I test backup2swift to archive backups on the OVH Public Cloud Archive. It has access via the Swift API.
https://docs.ovh.com/fr/fr/cloud/public-cloud/debuter-avec-lapi-swift/

I created a configuration file as shown in the documentation.
I can connect to the container with the Python swift command, but with backup2swift I have an error message:

$ ./bu2sw -c ./bu2sw.conf --container PCA -v -p file.dat 
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File ".../lib/python3.5/site-packages/backup2swift/backup.py", line 60, in backup
    self.backup_file(target_path)
  File ".../lib/python3.5/site-packages/backup2swift/backup.py", line 73, in backup_file
    if not self.client.containers.show_metadata(self.container_name).ok:
  File ".../lib/python3.5/site-packages/swiftsc/client.py", line 238, in show_metadata
    timeout=self.timeout)
  File ".../lib/python3.5/site-packages/requests/api.py", line 98, in head
    return request('head', url, **kwargs)
  File ".../lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File ".../lib/python3.5/site-packages/requests/sessions.py", line 499, in request
    prep = self.prepare_request(req)
  File ".../lib/python3.5/site-packages/requests/sessions.py", line 431, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File ".../lib/python3.5/site-packages/requests/models.py", line 303, in prepare
    self.prepare_url(url, params)
  File ".../lib/python3.5/site-packages/requests/models.py", line 377, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None/PCA': No schema supplied. Perhaps you meant http://None/PCA?

Regards.

**Comment by ghost** [comment]
Hello,

I've the same error but when I add my keystone tenant_id to config file like :

```
[keystone]
tenant_id: my_tenant_id
```

I obtain this error :

```
Traceback (most recent call last):
  File "/home/USER/.local/bin/bu2sw", line 11, in <module>
    sys.exit(main())
  File "/home/USER/.local/lib/python3.5/site-packages/backup2swift/command.py", line 125, in main
    args.func(args)
  File "/home/USER/.local/lib/python3.5/site-packages/backup2swift/command.py", line 97, in execute_swift_client
    container_name=container_name)
  File "/home/USER/.local/lib/python3.5/site-packages/backup2swift/backup.py", line 33, in __init__
    timeout=kwargs.get('timeout'))
  File "/home/USER/.local/lib/python3.5/site-packages/swiftsc/client.py", line 156, in __init__
    _keystone_auth(self)
  File "/home/USER/.local/lib/python3.5/site-packages/swiftsc/client.py", line 70, in _keystone_auth
    payload = _keystone_auth_payload(obj)
  File "/home/USER/.local/lib/python3.5/site-packages/swiftsc/client.py", line 54, in _keystone_auth_payload
    return payload
UnboundLocalError: local variable 'payload' referenced before assignment
```

Can you help ?

Regards
